// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: logger.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogSeverity int32

const (
	LogSeverity_DEBUG    LogSeverity = 0
	LogSeverity_INFO     LogSeverity = 1
	LogSeverity_WARNING  LogSeverity = 2
	LogSeverity_ERROR    LogSeverity = 3
	LogSeverity_CRITICAL LogSeverity = 4
)

// Enum value maps for LogSeverity.
var (
	LogSeverity_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
		4: "CRITICAL",
	}
	LogSeverity_value = map[string]int32{
		"DEBUG":    0,
		"INFO":     1,
		"WARNING":  2,
		"ERROR":    3,
		"CRITICAL": 4,
	}
)

func (x LogSeverity) Enum() *LogSeverity {
	p := new(LogSeverity)
	*p = x
	return p
}

func (x LogSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_logger_proto_enumTypes[0].Descriptor()
}

func (LogSeverity) Type() protoreflect.EnumType {
	return &file_logger_proto_enumTypes[0]
}

func (x LogSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSeverity.Descriptor instead.
func (LogSeverity) EnumDescriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{0}
}

// 서버 타입
type ServerType int32

const (
	ServerType_UNKNOWN  ServerType = 0
	ServerType_INGAME   ServerType = 1
	ServerType_QUESTION ServerType = 2
	ServerType_RANKING  ServerType = 3
	ServerType_OUTGAME  ServerType = 4
	ServerType_STATS    ServerType = 5
	ServerType_LOGGING  ServerType = 6
)

// Enum value maps for ServerType.
var (
	ServerType_name = map[int32]string{
		0: "UNKNOWN",
		1: "INGAME",
		2: "QUESTION",
		3: "RANKING",
		4: "OUTGAME",
		5: "STATS",
		6: "LOGGING",
	}
	ServerType_value = map[string]int32{
		"UNKNOWN":  0,
		"INGAME":   1,
		"QUESTION": 2,
		"RANKING":  3,
		"OUTGAME":  4,
		"STATS":    5,
		"LOGGING":  6,
	}
)

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerType) Descriptor() protoreflect.EnumDescriptor {
	return file_logger_proto_enumTypes[1].Descriptor()
}

func (ServerType) Type() protoreflect.EnumType {
	return &file_logger_proto_enumTypes[1]
}

func (x ServerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerType.Descriptor instead.
func (ServerType) EnumDescriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{1}
}

// 1-15: 공통필드
// 16-99: 서버
// 100-199: 클라이언트
type LogRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LogId             string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`                        // 로그 고유 ID
	RequestId         string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`            // HTTP/WebSocket 요청 ID
	SessionId         string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`            // 게임 세션 ID
	ServerId          string                 `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`               // 서버 인스턴스  ID
	EventType         string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`            // 이벤트 타입 (예: "game_session_start")
	Severity          LogSeverity            `protobuf:"varint,6,opt,name=severity,proto3,enum=log_message.LogSeverity" json:"severity,omitempty"` // 로그 레벨
	ServerTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`         // 서버 타임스탬프
	ServiceType       ServerType             `protobuf:"varint,8,opt,name=service_type,json=serviceType,proto3,enum=log_message.ServerType" json:"service_type,omitempty"`
	ServiceName       string                 `protobuf:"bytes,9,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`           // "ingame-server-1"
	ServiceVersion    string                 `protobuf:"bytes,10,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"` // "v1.2.3"
	Environment       string                 `protobuf:"bytes,11,opt,name=environment,proto3" json:"environment,omitempty"`                             // "prod", "staging", "dev"
	ServerIp          string                 `protobuf:"bytes,12,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	DurationMs        int64                  `protobuf:"varint,13,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`                      // 처리 시간 (밀리초)
	StatusCode        int32                  `protobuf:"varint,14,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                      // HTTP/gRPC 상태 코드
	Method            string                 `protobuf:"bytes,15,opt,name=method,proto3" json:"method,omitempty"`                                                 // HTTP 메서드 또는 RPC 메서드명
	Endpoint          string                 `protobuf:"bytes,16,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                             // API 엔드포인트 경로
	MemoryUsageMb     int64                  `protobuf:"varint,17,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`           // 메모리 사용량
	CpuUsagePercent   float32                `protobuf:"fixed32,18,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`    // CPU 사용률
	GoroutineCount    int32                  `protobuf:"varint,40,opt,name=goroutine_count,json=goroutineCount,proto3" json:"goroutine_count,omitempty"`          // Goroutine 수 (Go 특화)
	ActiveConnections int32                  `protobuf:"varint,41,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"` // 활성 연결 수
	GameMode          string                 `protobuf:"bytes,42,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`                             // "classic", "challenge"
	RoomId            string                 `protobuf:"bytes,43,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                   // 게임 방 ID
	Data              string                 `protobuf:"bytes,44,opt,name=data,proto3" json:"data,omitempty"`                                                     // JSON 페이로드 (유연한 추가 데이터)
	// ========== Client ===========
	ClientIp string `protobuf:"bytes,100,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"` // 클라이언트 IP (보안 감사용)
	UserId   string `protobuf:"bytes,101,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 사용자 ID (있는경우)
	DeviceId string `protobuf:"bytes,102,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// app info
	GameVersion string `protobuf:"bytes,103,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`
	Platform    string `protobuf:"bytes,104,opt,name=platform,proto3" json:"platform,omitempty"`
	OsVersion   string `protobuf:"bytes,105,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	DeviceModel string `protobuf:"bytes,106,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	// localization
	CountryCode string `protobuf:"bytes,107,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Language    string `protobuf:"bytes,108,opt,name=language,proto3" json:"language,omitempty"`
	Timezone    string `protobuf:"bytes,109,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Region      string `protobuf:"bytes,110,opt,name=region,proto3" json:"region,omitempty"`
	// network
	NetworkType         string  `protobuf:"bytes,111,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	PingMs              string  `protobuf:"bytes,112,opt,name=ping_ms,json=pingMs,proto3" json:"ping_ms,omitempty"`
	Fps                 int32   `protobuf:"varint,113,opt,name=fps,proto3" json:"fps,omitempty"`
	ClientMemoryUsageMb int64   `protobuf:"varint,114,opt,name=client_memory_usage_mb,json=clientMemoryUsageMb,proto3" json:"client_memory_usage_mb,omitempty"`
	ClientCpuUsageCount float32 `protobuf:"fixed32,115,opt,name=client_cpu_usage_count,json=clientCpuUsageCount,proto3" json:"client_cpu_usage_count,omitempty"`
	ClientData          string  `protobuf:"bytes,116,opt,name=client_data,json=clientData,proto3" json:"client_data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *LogRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *LogRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LogRequest) GetSeverity() LogSeverity {
	if x != nil {
		return x.Severity
	}
	return LogSeverity_DEBUG
}

func (x *LogRequest) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *LogRequest) GetServiceType() ServerType {
	if x != nil {
		return x.ServiceType
	}
	return ServerType_UNKNOWN
}

func (x *LogRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogRequest) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *LogRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *LogRequest) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

func (x *LogRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *LogRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *LogRequest) GetMemoryUsageMb() int64 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *LogRequest) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *LogRequest) GetGoroutineCount() int32 {
	if x != nil {
		return x.GoroutineCount
	}
	return 0
}

func (x *LogRequest) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *LogRequest) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

func (x *LogRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LogRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LogRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LogRequest) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

func (x *LogRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LogRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *LogRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *LogRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *LogRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LogRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *LogRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LogRequest) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *LogRequest) GetPingMs() string {
	if x != nil {
		return x.PingMs
	}
	return ""
}

func (x *LogRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *LogRequest) GetClientMemoryUsageMb() int64 {
	if x != nil {
		return x.ClientMemoryUsageMb
	}
	return 0
}

func (x *LogRequest) GetClientCpuUsageCount() float32 {
	if x != nil {
		return x.ClientCpuUsageCount
	}
	return 0
}

func (x *LogRequest) GetClientData() string {
	if x != nil {
		return x.ClientData
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_logger_proto protoreflect.FileDescriptor

const file_logger_proto_rawDesc = "" +
	"\n" +
	"\flogger.proto\x12\vlog_message\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\n" +
	"\n" +
	"\n" +
	"LogRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x124\n" +
	"\bseverity\x18\x06 \x01(\x0e2\x18.log_message.LogSeverityR\bseverity\x12;\n" +
	"\vserver_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12:\n" +
	"\fservice_type\x18\b \x01(\x0e2\x17.log_message.ServerTypeR\vserviceType\x12!\n" +
	"\fservice_name\x18\t \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\n" +
	" \x01(\tR\x0eserviceVersion\x12 \n" +
	"\venvironment\x18\v \x01(\tR\venvironment\x12\x1b\n" +
	"\tserver_ip\x18\f \x01(\tR\bserverIp\x12\x1f\n" +
	"\vduration_ms\x18\r \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vstatus_code\x18\x0e \x01(\x05R\n" +
	"statusCode\x12\x16\n" +
	"\x06method\x18\x0f \x01(\tR\x06method\x12\x1a\n" +
	"\bendpoint\x18\x10 \x01(\tR\bendpoint\x12&\n" +
	"\x0fmemory_usage_mb\x18\x11 \x01(\x03R\rmemoryUsageMb\x12*\n" +
	"\x11cpu_usage_percent\x18\x12 \x01(\x02R\x0fcpuUsagePercent\x12'\n" +
	"\x0fgoroutine_count\x18( \x01(\x05R\x0egoroutineCount\x12-\n" +
	"\x12active_connections\x18) \x01(\x05R\x11activeConnections\x12\x1b\n" +
	"\tgame_mode\x18* \x01(\tR\bgameMode\x12\x17\n" +
	"\aroom_id\x18+ \x01(\tR\x06roomId\x12\x12\n" +
	"\x04data\x18, \x01(\tR\x04data\x12\x1b\n" +
	"\tclient_ip\x18d \x01(\tR\bclientIp\x12\x17\n" +
	"\auser_id\x18e \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18f \x01(\tR\bdeviceId\x12!\n" +
	"\fgame_version\x18g \x01(\tR\vgameVersion\x12\x1a\n" +
	"\bplatform\x18h \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"os_version\x18i \x01(\tR\tosVersion\x12!\n" +
	"\fdevice_model\x18j \x01(\tR\vdeviceModel\x12!\n" +
	"\fcountry_code\x18k \x01(\tR\vcountryCode\x12\x1a\n" +
	"\blanguage\x18l \x01(\tR\blanguage\x12\x1a\n" +
	"\btimezone\x18m \x01(\tR\btimezone\x12\x16\n" +
	"\x06region\x18n \x01(\tR\x06region\x12!\n" +
	"\fnetwork_type\x18o \x01(\tR\vnetworkType\x12\x17\n" +
	"\aping_ms\x18p \x01(\tR\x06pingMs\x12\x10\n" +
	"\x03fps\x18q \x01(\x05R\x03fps\x123\n" +
	"\x16client_memory_usage_mb\x18r \x01(\x03R\x13clientMemoryUsageMb\x123\n" +
	"\x16client_cpu_usage_count\x18s \x01(\x02R\x13clientCpuUsageCount\x12\x1f\n" +
	"\vclient_data\x18t \x01(\tR\n" +
	"clientData\"A\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*H\n" +
	"\vLogSeverity\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04*e\n" +
	"\n" +
	"ServerType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06INGAME\x10\x01\x12\f\n" +
	"\bQUESTION\x10\x02\x12\v\n" +
	"\aRANKING\x10\x03\x12\v\n" +
	"\aOUTGAME\x10\x04\x12\t\n" +
	"\x05STATS\x10\x05\x12\v\n" +
	"\aLOGGING\x10\x062F\n" +
	"\x06Logger\x12<\n" +
	"\aSendLog\x12\x17.log_message.LogRequest\x1a\x18.log_message.LogResponseB\x13Z\x11logging/pb/clientb\x06proto3"

var (
	file_logger_proto_rawDescOnce sync.Once
	file_logger_proto_rawDescData []byte
)

func file_logger_proto_rawDescGZIP() []byte {
	file_logger_proto_rawDescOnce.Do(func() {
		file_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logger_proto_rawDesc), len(file_logger_proto_rawDesc)))
	})
	return file_logger_proto_rawDescData
}

var file_logger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logger_proto_goTypes = []any{
	(LogSeverity)(0),              // 0: log_message.LogSeverity
	(ServerType)(0),               // 1: log_message.ServerType
	(*LogRequest)(nil),            // 2: log_message.LogRequest
	(*LogResponse)(nil),           // 3: log_message.LogResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_logger_proto_depIdxs = []int32{
	0, // 0: log_message.LogRequest.severity:type_name -> log_message.LogSeverity
	4, // 1: log_message.LogRequest.server_time:type_name -> google.protobuf.Timestamp
	1, // 2: log_message.LogRequest.service_type:type_name -> log_message.ServerType
	2, // 3: log_message.Logger.SendLog:input_type -> log_message.LogRequest
	3, // 4: log_message.Logger.SendLog:output_type -> log_message.LogResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logger_proto_init() }
func file_logger_proto_init() {
	if File_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logger_proto_rawDesc), len(file_logger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logger_proto_goTypes,
		DependencyIndexes: file_logger_proto_depIdxs,
		EnumInfos:         file_logger_proto_enumTypes,
		MessageInfos:      file_logger_proto_msgTypes,
	}.Build()
	File_logger_proto = out.File
	file_logger_proto_goTypes = nil
	file_logger_proto_depIdxs = nil
}
