// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.query.sql

package sqlc

import (
	"context"
)

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, display_order, name
FROM categories
ORDER BY display_order
`

// GetAllCategories
//
//	SELECT id, display_order, name
//	FROM categories
//	ORDER BY display_order
func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.DisplayOrder, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategoryIds = `-- name: GetAllCategoryIds :many
SELECT id
FROM categories
`

// GetAllCategoryIds
//
//	SELECT id
//	FROM categories
func (q *Queries) GetAllCategoryIds(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, getAllCategoryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT id, display_order, name
FROM categories
WHERE id = $1
LIMIT 1
`

// GetCategoryById
//
//	SELECT id, display_order, name
//	FROM categories
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) GetCategoryById(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryById, id)
	var i Category
	err := row.Scan(&i.ID, &i.DisplayOrder, &i.Name)
	return i, err
}

const getCategoryByOrder = `-- name: GetCategoryByOrder :one
SELECT id, display_order, name
FROM categories
WHERE display_order = $1
LIMIT 1
`

// GetCategoryByOrder
//
//	SELECT id, display_order, name
//	FROM categories
//	WHERE display_order = $1
//	LIMIT 1
func (q *Queries) GetCategoryByOrder(ctx context.Context, displayOrder int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByOrder, displayOrder)
	var i Category
	err := row.Scan(&i.ID, &i.DisplayOrder, &i.Name)
	return i, err
}
