// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateQuestions implements pgx.CopyFromSource.
type iteratorForCreateQuestions struct {
	rows                 []CreateQuestionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateQuestions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateQuestions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].GameTypeID,
		r.rows[0].CategoryID,
		r.rows[0].Text,
		r.rows[0].Choices,
		r.rows[0].Explanation,
		r.rows[0].AnswerIndex,
	}, nil
}

func (r iteratorForCreateQuestions) Err() error {
	return nil
}

// CreateQuestions
//
//	INSERT INTO questions (game_type_id,
//	                       category_id,
//	                       text,
//	                       choices,
//	                       explanation,
//	                       answer_index)
//	VALUES ($1, $2, $3, $4, $5, $6)
func (q *Queries) CreateQuestions(ctx context.Context, arg []CreateQuestionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"questions"}, []string{"game_type_id", "category_id", "text", "choices", "explanation", "answer_index"}, &iteratorForCreateQuestions{rows: arg})
}
