// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: daily-rewards.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDailyReward = `-- name: CreateDailyReward :one
INSERT INTO daily_rewards
(user_id, started_at, ended_at, current_day, current_card_index, cards_start_index)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, current_day, current_card_index, cards_start_index, started_at, ended_at
`

type CreateDailyRewardParams struct {
	UserID           int64              `db:"user_id" json:"user_id"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt          pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CurrentDay       int32              `db:"current_day" json:"current_day"`
	CurrentCardIndex int32              `db:"current_card_index" json:"current_card_index"`
	CardsStartIndex  int32              `db:"cards_start_index" json:"cards_start_index"`
}

// CreateDailyReward
//
//	INSERT INTO daily_rewards
//	(user_id, started_at, ended_at, current_day, current_card_index, cards_start_index)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	RETURNING user_id, current_day, current_card_index, cards_start_index, started_at, ended_at
func (q *Queries) CreateDailyReward(ctx context.Context, arg CreateDailyRewardParams) (DailyReward, error) {
	row := q.db.QueryRow(ctx, createDailyReward,
		arg.UserID,
		arg.StartedAt,
		arg.EndedAt,
		arg.CurrentDay,
		arg.CurrentCardIndex,
		arg.CardsStartIndex,
	)
	var i DailyReward
	err := row.Scan(
		&i.UserID,
		&i.CurrentDay,
		&i.CurrentCardIndex,
		&i.CardsStartIndex,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createDailyRewardsBoxClaims = `-- name: CreateDailyRewardsBoxClaims :exec
INSERT INTO user_dr_box_claims
    (user_id, box_id, claimed_at)
VALUES ($1, $2, NOW())
`

type CreateDailyRewardsBoxClaimsParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	BoxID  int32 `db:"box_id" json:"box_id"`
}

// CreateDailyRewardsBoxClaims
//
//	INSERT INTO user_dr_box_claims
//	    (user_id, box_id, claimed_at)
//	VALUES ($1, $2, NOW())
func (q *Queries) CreateDailyRewardsBoxClaims(ctx context.Context, arg CreateDailyRewardsBoxClaimsParams) error {
	_, err := q.db.Exec(ctx, createDailyRewardsBoxClaims, arg.UserID, arg.BoxID)
	return err
}

const createDailyRewardsCardClaims = `-- name: CreateDailyRewardsCardClaims :exec
INSERT INTO user_dr_card_claims
    (user_id, card_id, claimed_at)
VALUES ($1, $2, NOW())
`

type CreateDailyRewardsCardClaimsParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	CardID int32 `db:"card_id" json:"card_id"`
}

// CreateDailyRewardsCardClaims
//
//	INSERT INTO user_dr_card_claims
//	    (user_id, card_id, claimed_at)
//	VALUES ($1, $2, NOW())
func (q *Queries) CreateDailyRewardsCardClaims(ctx context.Context, arg CreateDailyRewardsCardClaimsParams) error {
	_, err := q.db.Exec(ctx, createDailyRewardsCardClaims, arg.UserID, arg.CardID)
	return err
}

const getAllDailyRewardsBoxRewardsByType = `-- name: GetAllDailyRewardsBoxRewardsByType :many
SELECT id, type, day, quantity
FROM dr_boxes
`

// GetAllDailyRewardsBoxRewardsByType
//
//	SELECT id, type, day, quantity
//	FROM dr_boxes
func (q *Queries) GetAllDailyRewardsBoxRewardsByType(ctx context.Context) ([]DrBox, error) {
	rows, err := q.db.Query(ctx, getAllDailyRewardsBoxRewardsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DrBox
	for rows.Next() {
		var i DrBox
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Day,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDailyRewardsBoxes = `-- name: GetAllDailyRewardsBoxes :many
SELECT id, type, day, quantity
FROM dr_boxes
`

// GetAllDailyRewardsBoxes
//
//	SELECT id, type, day, quantity
//	FROM dr_boxes
func (q *Queries) GetAllDailyRewardsBoxes(ctx context.Context) ([]DrBox, error) {
	rows, err := q.db.Query(ctx, getAllDailyRewardsBoxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DrBox
	for rows.Next() {
		var i DrBox
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Day,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyReward = `-- name: GetDailyReward :one
SELECT user_id, current_day, current_card_index, cards_start_index, started_at, ended_at
FROM daily_rewards
WHERE user_id = $1
LIMIT 1
`

// GetDailyReward
//
//	SELECT user_id, current_day, current_card_index, cards_start_index, started_at, ended_at
//	FROM daily_rewards
//	WHERE user_id = $1
//	LIMIT 1
func (q *Queries) GetDailyReward(ctx context.Context, userID int64) (DailyReward, error) {
	row := q.db.QueryRow(ctx, getDailyReward, userID)
	var i DailyReward
	err := row.Scan(
		&i.UserID,
		&i.CurrentDay,
		&i.CurrentCardIndex,
		&i.CardsStartIndex,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getDailyRewardsBoxClaims = `-- name: GetDailyRewardsBoxClaims :many
SELECT id, user_id, box_id, claimed_at
FROM user_dr_box_claims
WHERE user_id = $1
`

// GetDailyRewardsBoxClaims
//
//	SELECT id, user_id, box_id, claimed_at
//	FROM user_dr_box_claims
//	WHERE user_id = $1
func (q *Queries) GetDailyRewardsBoxClaims(ctx context.Context, userID int64) ([]UserDrBoxClaim, error) {
	rows, err := q.db.Query(ctx, getDailyRewardsBoxClaims, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDrBoxClaim
	for rows.Next() {
		var i UserDrBoxClaim
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BoxID,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyRewardsCardClaims = `-- name: GetDailyRewardsCardClaims :many
SELECT id, user_id, card_id, claimed_at
FROM user_dr_card_claims
WHERE user_id = $1
`

// GetDailyRewardsCardClaims
//
//	SELECT id, user_id, card_id, claimed_at
//	FROM user_dr_card_claims
//	WHERE user_id = $1
func (q *Queries) GetDailyRewardsCardClaims(ctx context.Context, userID int64) ([]UserDrCardClaim, error) {
	rows, err := q.db.Query(ctx, getDailyRewardsCardClaims, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDrCardClaim
	for rows.Next() {
		var i UserDrCardClaim
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyRewardsCardRewardsByCardIds = `-- name: GetDailyRewardsCardRewardsByCardIds :many
SELECT id, card_id, type, quantity
FROM dr_card_rewards
WHERE card_id = $1
`

// GetDailyRewardsCardRewardsByCardIds
//
//	SELECT id, card_id, type, quantity
//	FROM dr_card_rewards
//	WHERE card_id = $1
func (q *Queries) GetDailyRewardsCardRewardsByCardIds(ctx context.Context, cardID int32) ([]DrCardReward, error) {
	rows, err := q.db.Query(ctx, getDailyRewardsCardRewardsByCardIds, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DrCardReward
	for rows.Next() {
		var i DrCardReward
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Type,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyRewardsCards = `-- name: GetDailyRewardsCards :many
SELECT id, day
FROM dr_cards
ORDER BY id
LIMIT $1 OFFSET $2
`

type GetDailyRewardsCardsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// GetDailyRewardsCards
//
//	SELECT id, day
//	FROM dr_cards
//	ORDER BY id
//	LIMIT $1 OFFSET $2
func (q *Queries) GetDailyRewardsCards(ctx context.Context, arg GetDailyRewardsCardsParams) ([]DrCard, error) {
	rows, err := q.db.Query(ctx, getDailyRewardsCards, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DrCard
	for rows.Next() {
		var i DrCard
		if err := rows.Scan(&i.ID, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyRewardsTimer = `-- name: GetDailyRewardsTimer :one
SELECT started_at,
       ended_at
FROM daily_rewards
WHERE user_id = $1
LIMIT 1
`

type GetDailyRewardsTimerRow struct {
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

// GetDailyRewardsTimer
//
//	SELECT started_at,
//	       ended_at
//	FROM daily_rewards
//	WHERE user_id = $1
//	LIMIT 1
func (q *Queries) GetDailyRewardsTimer(ctx context.Context, userID int64) (GetDailyRewardsTimerRow, error) {
	row := q.db.QueryRow(ctx, getDailyRewardsTimer, userID)
	var i GetDailyRewardsTimerRow
	err := row.Scan(&i.StartedAt, &i.EndedAt)
	return i, err
}

const resetDailyReward = `-- name: ResetDailyReward :exec
DELETE
FROM daily_rewards
WHERE user_id = $1
`

// ResetDailyReward
//
//	DELETE
//	FROM daily_rewards
//	WHERE user_id = $1
func (q *Queries) ResetDailyReward(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, resetDailyReward, userID)
	return err
}

const resetDailyRewardsBoxClaim = `-- name: ResetDailyRewardsBoxClaim :exec
DELETE
FROM user_dr_box_claims
WHERE user_id = $1
`

// ResetDailyRewardsBoxClaim
//
//	DELETE
//	FROM user_dr_box_claims
//	WHERE user_id = $1
func (q *Queries) ResetDailyRewardsBoxClaim(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, resetDailyRewardsBoxClaim, userID)
	return err
}

const resetDailyRewardsCardClaim = `-- name: ResetDailyRewardsCardClaim :exec
DELETE
FROM user_dr_card_claims
WHERE user_id = $1
`

// ResetDailyRewardsCardClaim
//
//	DELETE
//	FROM user_dr_card_claims
//	WHERE user_id = $1
func (q *Queries) ResetDailyRewardsCardClaim(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, resetDailyRewardsCardClaim, userID)
	return err
}

const updateDailyReward = `-- name: UpdateDailyReward :exec
UPDATE daily_rewards
SET started_at        =$2,
    ended_at          =$3,
    current_card_index=$4,
    current_day=$5,
    cards_start_index=$6
WHERE user_id = $1
`

type UpdateDailyRewardParams struct {
	UserID           int64              `db:"user_id" json:"user_id"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt          pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CurrentCardIndex int32              `db:"current_card_index" json:"current_card_index"`
	CurrentDay       int32              `db:"current_day" json:"current_day"`
	CardsStartIndex  int32              `db:"cards_start_index" json:"cards_start_index"`
}

// UpdateDailyReward
//
//	UPDATE daily_rewards
//	SET started_at        =$2,
//	    ended_at          =$3,
//	    current_card_index=$4,
//	    current_day=$5,
//	    cards_start_index=$6
//	WHERE user_id = $1
func (q *Queries) UpdateDailyReward(ctx context.Context, arg UpdateDailyRewardParams) error {
	_, err := q.db.Exec(ctx, updateDailyReward,
		arg.UserID,
		arg.StartedAt,
		arg.EndedAt,
		arg.CurrentCardIndex,
		arg.CurrentDay,
		arg.CardsStartIndex,
	)
	return err
}
