// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game_configs.query.sql

package sqlc

import (
	"context"
)

const getDefaultConfig = `-- name: GetDefaultConfig :one
SELECT id, coin_balance, gem_balance, coin_rewards, crown_rewards, max_stage_quantity, hint_quantity, skip_quantity, initial_game_time_left, ingame_server_ip_addr, continue_price, continue_price_type, hint_recharge_price, hint_recharge_price_type, skip_recharge_price, skip_recharge_price_type, daily_rewards_last_day, daily_rewards_box_count, daily_rewards_cards_count_per_week, lucky_spin_cooltime, daily_rewards_cooltime, daily_rewards_card_claim_grace_period
FROM game_configs
LIMIT 1
`

// GetDefaultConfig
//
//	SELECT id, coin_balance, gem_balance, coin_rewards, crown_rewards, max_stage_quantity, hint_quantity, skip_quantity, initial_game_time_left, ingame_server_ip_addr, continue_price, continue_price_type, hint_recharge_price, hint_recharge_price_type, skip_recharge_price, skip_recharge_price_type, daily_rewards_last_day, daily_rewards_box_count, daily_rewards_cards_count_per_week, lucky_spin_cooltime, daily_rewards_cooltime, daily_rewards_card_claim_grace_period
//	FROM game_configs
//	LIMIT 1
func (q *Queries) GetDefaultConfig(ctx context.Context) (GameConfig, error) {
	row := q.db.QueryRow(ctx, getDefaultConfig)
	var i GameConfig
	err := row.Scan(
		&i.ID,
		&i.CoinBalance,
		&i.GemBalance,
		&i.CoinRewards,
		&i.CrownRewards,
		&i.MaxStageQuantity,
		&i.HintQuantity,
		&i.SkipQuantity,
		&i.InitialGameTimeLeft,
		&i.IngameServerIpAddr,
		&i.ContinuePrice,
		&i.ContinuePriceType,
		&i.HintRechargePrice,
		&i.HintRechargePriceType,
		&i.SkipRechargePrice,
		&i.SkipRechargePriceType,
		&i.DailyRewardsLastDay,
		&i.DailyRewardsBoxCount,
		&i.DailyRewardsCardsCountPerWeek,
		&i.LuckySpinCooltime,
		&i.DailyRewardsCooltime,
		&i.DailyRewardsCardClaimGracePeriod,
	)
	return i, err
}
