// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game_types.query.sql

package sqlc

import (
	"context"
)

const getAllGameTypeIds = `-- name: GetAllGameTypeIds :many
SELECT id
FROM game_types
`

// GetAllGameTypeIds
//
//	SELECT id
//	FROM game_types
func (q *Queries) GetAllGameTypeIds(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, getAllGameTypeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGameTypes = `-- name: GetAllGameTypes :many
SELECT id, name, entrance_fee
FROM game_types
`

// GetAllGameTypes
//
//	SELECT id, name, entrance_fee
//	FROM game_types
func (q *Queries) GetAllGameTypes(ctx context.Context) ([]GameType, error) {
	rows, err := q.db.Query(ctx, getAllGameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameType
	for rows.Next() {
		var i GameType
		if err := rows.Scan(&i.ID, &i.Name, &i.EntranceFee); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameTypeById = `-- name: GetGameTypeById :one
SELECT id, name, entrance_fee
FROM game_types
WHERE id = $1
`

// GetGameTypeById
//
//	SELECT id, name, entrance_fee
//	FROM game_types
//	WHERE id = $1
func (q *Queries) GetGameTypeById(ctx context.Context, id int32) (GameType, error) {
	row := q.db.QueryRow(ctx, getGameTypeById, id)
	var i GameType
	err := row.Scan(&i.ID, &i.Name, &i.EntranceFee)
	return i, err
}
