// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inventories.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGameItems = `-- name: GetGameItems :one
SELECT hint_quantity,
       skip_quantity
FROM users
WHERE id = $1
`

type GetGameItemsRow struct {
	HintQuantity int32 `db:"hint_quantity" json:"hint_quantity"`
	SkipQuantity int32 `db:"skip_quantity" json:"skip_quantity"`
}

// GetGameItems
//
//	SELECT hint_quantity,
//	       skip_quantity
//	FROM users
//	WHERE id = $1
func (q *Queries) GetGameItems(ctx context.Context, id int64) (GetGameItemsRow, error) {
	row := q.db.QueryRow(ctx, getGameItems, id)
	var i GetGameItemsRow
	err := row.Scan(&i.HintQuantity, &i.SkipQuantity)
	return i, err
}

const getHint = `-- name: GetHint :one
SELECT public_id,
       hint_quantity
FROM users
WHERE public_id = $1
`

type GetHintRow struct {
	PublicID     pgtype.UUID `db:"public_id" json:"public_id"`
	HintQuantity int32       `db:"hint_quantity" json:"hint_quantity"`
}

// GetHint
//
//	SELECT public_id,
//	       hint_quantity
//	FROM users
//	WHERE public_id = $1
func (q *Queries) GetHint(ctx context.Context, publicID pgtype.UUID) (GetHintRow, error) {
	row := q.db.QueryRow(ctx, getHint, publicID)
	var i GetHintRow
	err := row.Scan(&i.PublicID, &i.HintQuantity)
	return i, err
}

const getSkip = `-- name: GetSkip :one
SELECT public_id,
       skip_quantity
FROM users
WHERE public_id = $1
`

type GetSkipRow struct {
	PublicID     pgtype.UUID `db:"public_id" json:"public_id"`
	SkipQuantity int32       `db:"skip_quantity" json:"skip_quantity"`
}

// GetSkip
//
//	SELECT public_id,
//	       skip_quantity
//	FROM users
//	WHERE public_id = $1
func (q *Queries) GetSkip(ctx context.Context, publicID pgtype.UUID) (GetSkipRow, error) {
	row := q.db.QueryRow(ctx, getSkip, publicID)
	var i GetSkipRow
	err := row.Scan(&i.PublicID, &i.SkipQuantity)
	return i, err
}

const getUserInventory = `-- name: GetUserInventory :one
SELECT hint_quantity, skip_quantity, gem_balance, coin_balance
FROM users
WHERE id = $1
`

type GetUserInventoryRow struct {
	HintQuantity int32 `db:"hint_quantity" json:"hint_quantity"`
	SkipQuantity int32 `db:"skip_quantity" json:"skip_quantity"`
	GemBalance   int32 `db:"gem_balance" json:"gem_balance"`
	CoinBalance  int32 `db:"coin_balance" json:"coin_balance"`
}

// GetUserInventory
//
//	SELECT hint_quantity, skip_quantity, gem_balance, coin_balance
//	FROM users
//	WHERE id = $1
func (q *Queries) GetUserInventory(ctx context.Context, id int64) (GetUserInventoryRow, error) {
	row := q.db.QueryRow(ctx, getUserInventory, id)
	var i GetUserInventoryRow
	err := row.Scan(
		&i.HintQuantity,
		&i.SkipQuantity,
		&i.GemBalance,
		&i.CoinBalance,
	)
	return i, err
}

const updateHintQuantity = `-- name: UpdateHintQuantity :exec
UPDATE users
SET hint_quantity = $2
WHERE id = $1
`

type UpdateHintQuantityParams struct {
	ID           int64 `db:"id" json:"id"`
	HintQuantity int32 `db:"hint_quantity" json:"hint_quantity"`
}

// UpdateHintQuantity
//
//	UPDATE users
//	SET hint_quantity = $2
//	WHERE id = $1
func (q *Queries) UpdateHintQuantity(ctx context.Context, arg UpdateHintQuantityParams) error {
	_, err := q.db.Exec(ctx, updateHintQuantity, arg.ID, arg.HintQuantity)
	return err
}

const updateSkipQuantity = `-- name: UpdateSkipQuantity :exec
UPDATE users
SET skip_quantity = $2
WHERE id = $1
`

type UpdateSkipQuantityParams struct {
	ID           int64 `db:"id" json:"id"`
	SkipQuantity int32 `db:"skip_quantity" json:"skip_quantity"`
}

// UpdateSkipQuantity
//
//	UPDATE users
//	SET skip_quantity = $2
//	WHERE id = $1
func (q *Queries) UpdateSkipQuantity(ctx context.Context, arg UpdateSkipQuantityParams) error {
	_, err := q.db.Exec(ctx, updateSkipQuantity, arg.ID, arg.SkipQuantity)
	return err
}

const updateUserInventory = `-- name: UpdateUserInventory :exec
UPDATE users
SET hint_quantity = $2,
    skip_quantity = $3
WHERE id = $1
`

type UpdateUserInventoryParams struct {
	ID           int64 `db:"id" json:"id"`
	HintQuantity int32 `db:"hint_quantity" json:"hint_quantity"`
	SkipQuantity int32 `db:"skip_quantity" json:"skip_quantity"`
}

// UpdateUserInventory
//
//	UPDATE users
//	SET hint_quantity = $2,
//	    skip_quantity = $3
//	WHERE id = $1
func (q *Queries) UpdateUserInventory(ctx context.Context, arg UpdateUserInventoryParams) error {
	_, err := q.db.Exec(ctx, updateUserInventory, arg.ID, arg.HintQuantity, arg.SkipQuantity)
	return err
}
