// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.query.sql

package sqlc

import (
	"context"
)

const getAllItemIds = `-- name: GetAllItemIds :many
SELECT id
FROM items
`

// GetAllItemIds
//
//	SELECT id
//	FROM items
func (q *Queries) GetAllItemIds(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, getAllItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, name, item_type, price_type, price
FROM items
ORDER BY id
`

// GetAllItems
//
//	SELECT id, name, item_type, price_type, price
//	FROM items
//	ORDER BY id
func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.PriceType,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemById = `-- name: GetItemById :one
SELECT id, name, item_type, price_type, price
FROM items
WHERE id = $1
LIMIT 1
`

// GetItemById
//
//	SELECT id, name, item_type, price_type, price
//	FROM items
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) GetItemById(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRow(ctx, getItemById, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.PriceType,
		&i.Price,
	)
	return i, err
}

const getItemPrice = `-- name: GetItemPrice :one
SELECT price, price_type
FROM items
WHERE id = $1
`

type GetItemPriceRow struct {
	Price     int32     `db:"price" json:"price"`
	PriceType PriceType `db:"price_type" json:"price_type"`
}

// GetItemPrice
//
//	SELECT price, price_type
//	FROM items
//	WHERE id = $1
func (q *Queries) GetItemPrice(ctx context.Context, id int32) (GetItemPriceRow, error) {
	row := q.db.QueryRow(ctx, getItemPrice, id)
	var i GetItemPriceRow
	err := row.Scan(&i.Price, &i.PriceType)
	return i, err
}

const getItemPriceByType = `-- name: GetItemPriceByType :one
SELECT price, price_type
FROM items
WHERE item_type = $1
`

type GetItemPriceByTypeRow struct {
	Price     int32     `db:"price" json:"price"`
	PriceType PriceType `db:"price_type" json:"price_type"`
}

// GetItemPriceByType
//
//	SELECT price, price_type
//	FROM items
//	WHERE item_type = $1
func (q *Queries) GetItemPriceByType(ctx context.Context, itemType GameItemType) (GetItemPriceByTypeRow, error) {
	row := q.db.QueryRow(ctx, getItemPriceByType, itemType)
	var i GetItemPriceByTypeRow
	err := row.Scan(&i.Price, &i.PriceType)
	return i, err
}
