// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItems = `-- name: CountItems :one
SELECT COUNT(*) FROM items
`

// CountItems
//
//	SELECT COUNT(*) FROM items
func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    name,
    description,
    price,
    quantity
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, description, price, quantity, created_at, updated_at
`

type CreateItemParams struct {
	Name        string         `db:"name" json:"name"`
	Description pgtype.Text    `db:"description" json:"description"`
	Price       pgtype.Numeric `db:"price" json:"price"`
	Quantity    int32          `db:"quantity" json:"quantity"`
}

// CreateItem
//
//	INSERT INTO items (
//	    name,
//	    description,
//	    price,
//	    quantity
//	) VALUES (
//	    $1, $2, $3, $4
//	) RETURNING id, name, description, price, quantity, created_at, updated_at
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

// DeleteItem
//
//	DELETE FROM items
//	WHERE id = $1
func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, description, price, quantity, created_at, updated_at FROM items
WHERE id = $1
LIMIT 1
`

// GetItemByID
//
//	SELECT id, name, description, price, quantity, created_at, updated_at FROM items
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) GetItemByID(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLowStockItems = `-- name: GetLowStockItems :many
SELECT id, name, description, price, quantity, created_at, updated_at FROM items
WHERE quantity < $1
ORDER BY quantity ASC
`

// GetLowStockItems
//
//	SELECT id, name, description, price, quantity, created_at, updated_at FROM items
//	WHERE quantity < $1
//	ORDER BY quantity ASC
func (q *Queries) GetLowStockItems(ctx context.Context, quantity int32) ([]Item, error) {
	rows, err := q.db.Query(ctx, getLowStockItems, quantity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, name, description, price, quantity, created_at, updated_at FROM items
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListItemsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// ListItems
//
//	SELECT id, name, description, price, quantity, created_at, updated_at FROM items
//	ORDER BY created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemsByName = `-- name: SearchItemsByName :many
SELECT id, name, description, price, quantity, created_at, updated_at FROM items
WHERE name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchItemsByNameParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

// SearchItemsByName
//
//	SELECT id, name, description, price, quantity, created_at, updated_at FROM items
//	WHERE name ILIKE '%' || $1 || '%'
//	ORDER BY created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) SearchItemsByName(ctx context.Context, arg SearchItemsByNameParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, searchItemsByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    price = COALESCE($4, price),
    quantity = COALESCE($5, quantity)
WHERE id = $1
RETURNING id, name, description, price, quantity, created_at, updated_at
`

type UpdateItemParams struct {
	ID          int64          `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Description pgtype.Text    `db:"description" json:"description"`
	Price       pgtype.Numeric `db:"price" json:"price"`
	Quantity    int32          `db:"quantity" json:"quantity"`
}

// UpdateItem
//
//	UPDATE items
//	SET
//	    name = COALESCE($2, name),
//	    description = COALESCE($3, description),
//	    price = COALESCE($4, price),
//	    quantity = COALESCE($5, quantity)
//	WHERE id = $1
//	RETURNING id, name, description, price, quantity, created_at, updated_at
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemQuantity = `-- name: UpdateItemQuantity :one
UPDATE items
SET quantity = quantity + $2
WHERE id = $1
RETURNING id, name, description, price, quantity, created_at, updated_at
`

type UpdateItemQuantityParams struct {
	ID       int64 `db:"id" json:"id"`
	Quantity int32 `db:"quantity" json:"quantity"`
}

// UpdateItemQuantity
//
//	UPDATE items
//	SET quantity = quantity + $2
//	WHERE id = $1
//	RETURNING id, name, description, price, quantity, created_at, updated_at
func (q *Queries) UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemQuantity, arg.ID, arg.Quantity)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
