// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lucky_spin.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAndResetAdsOfSpin = `-- name: ClaimAndResetAdsOfSpin :exec
UPDATE public.user_ls_spins
SET was_ads = FALSE
WHERE user_id = $1
`

// ClaimAndResetAdsOfSpin
//
//	UPDATE public.user_ls_spins
//	SET was_ads = FALSE
//	WHERE user_id = $1
func (q *Queries) ClaimAndResetAdsOfSpin(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, claimAndResetAdsOfSpin, userID)
	return err
}

const createLuckySpin = `-- name: CreateLuckySpin :one
INSERT INTO user_ls_spins (user_id,
                           reward_id,
                           started_at,
                           ended_at,
                           was_ads)
VALUES ($1, $2, $3, $4, $5)
RETURNING started_at, ended_at
`

type CreateLuckySpinParams struct {
	UserID    int64              `db:"user_id" json:"user_id"`
	RewardID  int32              `db:"reward_id" json:"reward_id"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	WasAds    bool               `db:"was_ads" json:"was_ads"`
}

type CreateLuckySpinRow struct {
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

// CreateLuckySpin
//
//	INSERT INTO user_ls_spins (user_id,
//	                           reward_id,
//	                           started_at,
//	                           ended_at,
//	                           was_ads)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING started_at, ended_at
func (q *Queries) CreateLuckySpin(ctx context.Context, arg CreateLuckySpinParams) (CreateLuckySpinRow, error) {
	row := q.db.QueryRow(ctx, createLuckySpin,
		arg.UserID,
		arg.RewardID,
		arg.StartedAt,
		arg.EndedAt,
		arg.WasAds,
	)
	var i CreateLuckySpinRow
	err := row.Scan(&i.StartedAt, &i.EndedAt)
	return i, err
}

const createLuckySpinClaim = `-- name: CreateLuckySpinClaim :exec
INSERT INTO user_ls_claims (user_id,
                            reward_id,
                            quantity_at_claim,
                            type_at_claim,
                            claimed_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLuckySpinClaimParams struct {
	UserID          int64              `db:"user_id" json:"user_id"`
	RewardID        int32              `db:"reward_id" json:"reward_id"`
	QuantityAtClaim int32              `db:"quantity_at_claim" json:"quantity_at_claim"`
	TypeAtClaim     RewardType         `db:"type_at_claim" json:"type_at_claim"`
	ClaimedAt       pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
}

// CreateLuckySpinClaim
//
//	INSERT INTO user_ls_claims (user_id,
//	                            reward_id,
//	                            quantity_at_claim,
//	                            type_at_claim,
//	                            claimed_at)
//	VALUES ($1, $2, $3, $4, $5)
func (q *Queries) CreateLuckySpinClaim(ctx context.Context, arg CreateLuckySpinClaimParams) error {
	_, err := q.db.Exec(ctx, createLuckySpinClaim,
		arg.UserID,
		arg.RewardID,
		arg.QuantityAtClaim,
		arg.TypeAtClaim,
		arg.ClaimedAt,
	)
	return err
}

const getAllLuckySpinRewards = `-- name: GetAllLuckySpinRewards :many
SELECT id, type, quantity, spawn_probability
FROM public.ls_rewards
`

// GetAllLuckySpinRewards
//
//	SELECT id, type, quantity, spawn_probability
//	FROM public.ls_rewards
func (q *Queries) GetAllLuckySpinRewards(ctx context.Context) ([]LsReward, error) {
	rows, err := q.db.Query(ctx, getAllLuckySpinRewards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LsReward
	for rows.Next() {
		var i LsReward
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Quantity,
			&i.SpawnProbability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLuckySpin = `-- name: GetLuckySpin :one
SELECT id, user_id, reward_id, was_ads, started_at, ended_at
FROM public.user_ls_spins
WHERE user_id = $1
`

// GetLuckySpin
//
//	SELECT id, user_id, reward_id, was_ads, started_at, ended_at
//	FROM public.user_ls_spins
//	WHERE user_id = $1
func (q *Queries) GetLuckySpin(ctx context.Context, userID int64) (UserLsSpin, error) {
	row := q.db.QueryRow(ctx, getLuckySpin, userID)
	var i UserLsSpin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RewardID,
		&i.WasAds,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getLuckySpinReward = `-- name: GetLuckySpinReward :one
SELECT id, type, quantity, spawn_probability
FROM public.ls_rewards
WHERE id = $1
`

// GetLuckySpinReward
//
//	SELECT id, type, quantity, spawn_probability
//	FROM public.ls_rewards
//	WHERE id = $1
func (q *Queries) GetLuckySpinReward(ctx context.Context, id int32) (LsReward, error) {
	row := q.db.QueryRow(ctx, getLuckySpinReward, id)
	var i LsReward
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Quantity,
		&i.SpawnProbability,
	)
	return i, err
}

const getLuckySpinTimer = `-- name: GetLuckySpinTimer :one
SELECT started_at,
       ended_at
FROM user_ls_spins
WHERE user_id = $1
LIMIT 1
`

type GetLuckySpinTimerRow struct {
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

// GetLuckySpinTimer
//
//	SELECT started_at,
//	       ended_at
//	FROM user_ls_spins
//	WHERE user_id = $1
//	LIMIT 1
func (q *Queries) GetLuckySpinTimer(ctx context.Context, userID int64) (GetLuckySpinTimerRow, error) {
	row := q.db.QueryRow(ctx, getLuckySpinTimer, userID)
	var i GetLuckySpinTimerRow
	err := row.Scan(&i.StartedAt, &i.EndedAt)
	return i, err
}

const updateLuckySpin = `-- name: UpdateLuckySpin :exec
UPDATE user_ls_spins
SET reward_id  = $2,
    started_at = $3,
    ended_at   = $4,
    was_ads    = $5
WHERE user_id = $1
`

type UpdateLuckySpinParams struct {
	UserID    int64              `db:"user_id" json:"user_id"`
	RewardID  int32              `db:"reward_id" json:"reward_id"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	WasAds    bool               `db:"was_ads" json:"was_ads"`
}

// UpdateLuckySpin
//
//	UPDATE user_ls_spins
//	SET reward_id  = $2,
//	    started_at = $3,
//	    ended_at   = $4,
//	    was_ads    = $5
//	WHERE user_id = $1
func (q *Queries) UpdateLuckySpin(ctx context.Context, arg UpdateLuckySpinParams) error {
	_, err := q.db.Exec(ctx, updateLuckySpin,
		arg.UserID,
		arg.RewardID,
		arg.StartedAt,
		arg.EndedAt,
		arg.WasAds,
	)
	return err
}
