// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventPackageType string

const (
	EventPackageTypeAddict  EventPackageType = "addict"
	EventPackageType111     EventPackageType = "1+1_1"
	EventPackageType112     EventPackageType = "1+1_2"
	EventPackageTypeAddict2 EventPackageType = "addict2"
	EventPackageType113     EventPackageType = "1+1_3"
	EventPackageType114     EventPackageType = "1+1_4"
)

func (e *EventPackageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventPackageType(s)
	case string:
		*e = EventPackageType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventPackageType: %T", src)
	}
	return nil
}

type NullEventPackageType struct {
	EventPackageType EventPackageType `json:"event_package_type"`
	Valid            bool             `json:"valid"` // Valid is true if EventPackageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventPackageType) Scan(value interface{}) error {
	if value == nil {
		ns.EventPackageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventPackageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventPackageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventPackageType), nil
}

func AllEventPackageTypeValues() []EventPackageType {
	return []EventPackageType{
		EventPackageTypeAddict,
		EventPackageType111,
		EventPackageType112,
		EventPackageTypeAddict2,
		EventPackageType113,
		EventPackageType114,
	}
}

type GameItemType string

const (
	GameItemTypeSkip   GameItemType = "skip"
	GameItemTypeHint   GameItemType = "hint"
	GameItemTypeRemove GameItemType = "remove"
)

func (e *GameItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameItemType(s)
	case string:
		*e = GameItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for GameItemType: %T", src)
	}
	return nil
}

type NullGameItemType struct {
	GameItemType GameItemType `json:"game_item_type"`
	Valid        bool         `json:"valid"` // Valid is true if GameItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameItemType) Scan(value interface{}) error {
	if value == nil {
		ns.GameItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameItemType), nil
}

func AllGameItemTypeValues() []GameItemType {
	return []GameItemType{
		GameItemTypeSkip,
		GameItemTypeHint,
		GameItemTypeRemove,
	}
}

type PriceType string

const (
	PriceTypeGem  PriceType = "gem"
	PriceTypeCoin PriceType = "coin"
)

func (e *PriceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriceType(s)
	case string:
		*e = PriceType(s)
	default:
		return fmt.Errorf("unsupported scan type for PriceType: %T", src)
	}
	return nil
}

type NullPriceType struct {
	PriceType PriceType `json:"price_type"`
	Valid     bool      `json:"valid"` // Valid is true if PriceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceType) Scan(value interface{}) error {
	if value == nil {
		ns.PriceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriceType), nil
}

func AllPriceTypeValues() []PriceType {
	return []PriceType{
		PriceTypeGem,
		PriceTypeCoin,
	}
}

type QuestionStatus string

const (
	QuestionStatusUnsolved  QuestionStatus = "unsolved"
	QuestionStatusCorrect   QuestionStatus = "correct"
	QuestionStatusIncorrect QuestionStatus = "incorrect"
	QuestionStatusSkipped   QuestionStatus = "skipped"
)

func (e *QuestionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionStatus(s)
	case string:
		*e = QuestionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionStatus: %T", src)
	}
	return nil
}

type NullQuestionStatus struct {
	QuestionStatus QuestionStatus `json:"question_status"`
	Valid          bool           `json:"valid"` // Valid is true if QuestionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionStatus), nil
}

func AllQuestionStatusValues() []QuestionStatus {
	return []QuestionStatus{
		QuestionStatusUnsolved,
		QuestionStatusCorrect,
		QuestionStatusIncorrect,
		QuestionStatusSkipped,
	}
}

type RewardType string

const (
	RewardTypeGem    RewardType = "gem"
	RewardTypeCoin   RewardType = "coin"
	RewardTypeSkip   RewardType = "skip"
	RewardTypeHint   RewardType = "hint"
	RewardTypeRemove RewardType = "remove"
)

func (e *RewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RewardType(s)
	case string:
		*e = RewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for RewardType: %T", src)
	}
	return nil
}

type NullRewardType struct {
	RewardType RewardType `json:"reward_type"`
	Valid      bool       `json:"valid"` // Valid is true if RewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.RewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RewardType), nil
}

func AllRewardTypeValues() []RewardType {
	return []RewardType{
		RewardTypeGem,
		RewardTypeCoin,
		RewardTypeSkip,
		RewardTypeHint,
		RewardTypeRemove,
	}
}

type Category struct {
	ID           int32  `db:"id" json:"id"`
	DisplayOrder int32  `db:"display_order" json:"display_order"`
	Name         string `db:"name" json:"name"`
}

type DailyReward struct {
	UserID           int64              `db:"user_id" json:"user_id"`
	CurrentDay       int32              `db:"current_day" json:"current_day"`
	CurrentCardIndex int32              `db:"current_card_index" json:"current_card_index"`
	CardsStartIndex  int32              `db:"cards_start_index" json:"cards_start_index"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt          pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

type DrBox struct {
	ID       int32      `db:"id" json:"id"`
	Type     RewardType `db:"type" json:"type"`
	Day      int32      `db:"day" json:"day"`
	Quantity int32      `db:"quantity" json:"quantity"`
}

type DrCard struct {
	ID  int32 `db:"id" json:"id"`
	Day int32 `db:"day" json:"day"`
}

type DrCardReward struct {
	ID       int32      `db:"id" json:"id"`
	CardID   int32      `db:"card_id" json:"card_id"`
	Type     RewardType `db:"type" json:"type"`
	Quantity int32      `db:"quantity" json:"quantity"`
}

type EpDuration struct {
	UserID         int64              `db:"user_id" json:"user_id"`
	EventPackageID int32              `db:"event_package_id" json:"event_package_id"`
	StartedAt      pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ExpiredAt      pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EpReward struct {
	ID             int32 `db:"id" json:"id"`
	CoinQuantity   int32 `db:"coin_quantity" json:"coin_quantity"`
	GemQuantity    int32 `db:"gem_quantity" json:"gem_quantity"`
	HintQuantity   int32 `db:"hint_quantity" json:"hint_quantity"`
	SkipQuantity   int32 `db:"skip_quantity" json:"skip_quantity"`
	RemoveQuantity int32 `db:"remove_quantity" json:"remove_quantity"`
}

type EpSpawnTable struct {
	ID               int32       `db:"id" json:"id"`
	EventPackageID   int32       `db:"event_package_id" json:"event_package_id"`
	NextID           pgtype.Int4 `db:"next_id" json:"next_id"`
	SpawnProbability int32       `db:"spawn_probability" json:"spawn_probability"`
}

type EpTransaction struct {
	ID                  int32              `db:"id" json:"id"`
	UserID              int64              `db:"user_id" json:"user_id"`
	EventPackageID      int32              `db:"event_package_id" json:"event_package_id"`
	PurchasedQuantity   int32              `db:"purchased_quantity" json:"purchased_quantity"`
	PurchasedAt         pgtype.Timestamptz `db:"purchased_at" json:"purchased_at"`
	PriceAtPurchase     string             `db:"price_at_purchase" json:"price_at_purchase"`
	PriceUnitAtPurchase string             `db:"price_unit_at_purchase" json:"price_unit_at_purchase"`
}

type EventPackage struct {
	ID                  int32            `db:"id" json:"id"`
	DisplayName         string           `db:"display_name" json:"display_name"`
	MaxPurchaseQuantity int32            `db:"max_purchase_quantity" json:"max_purchase_quantity"`
	ExpiryDuration      int32            `db:"expiry_duration" json:"expiry_duration"`
	Type                EventPackageType `db:"type" json:"type"`
}

type EventPackageReward struct {
	EventPackageID int32 `db:"event_package_id" json:"event_package_id"`
	EpRewardID     int32 `db:"ep_reward_id" json:"ep_reward_id"`
	RewardOrder    int32 `db:"reward_order" json:"reward_order"`
}

type GameConfig struct {
	ID                               int32       `db:"id" json:"id"`
	CoinBalance                      int32       `db:"coin_balance" json:"coin_balance"`
	GemBalance                       int32       `db:"gem_balance" json:"gem_balance"`
	CoinRewards                      int32       `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards                     int32       `db:"crown_rewards" json:"crown_rewards"`
	MaxStageQuantity                 int32       `db:"max_stage_quantity" json:"max_stage_quantity"`
	HintQuantity                     int32       `db:"hint_quantity" json:"hint_quantity"`
	SkipQuantity                     int32       `db:"skip_quantity" json:"skip_quantity"`
	InitialGameTimeLeft              int32       `db:"initial_game_time_left" json:"initial_game_time_left"`
	IngameServerIpAddr               pgtype.Text `db:"ingame_server_ip_addr" json:"ingame_server_ip_addr"`
	ContinuePrice                    int32       `db:"continue_price" json:"continue_price"`
	ContinuePriceType                PriceType   `db:"continue_price_type" json:"continue_price_type"`
	HintRechargePrice                int32       `db:"hint_recharge_price" json:"hint_recharge_price"`
	HintRechargePriceType            PriceType   `db:"hint_recharge_price_type" json:"hint_recharge_price_type"`
	SkipRechargePrice                int32       `db:"skip_recharge_price" json:"skip_recharge_price"`
	SkipRechargePriceType            PriceType   `db:"skip_recharge_price_type" json:"skip_recharge_price_type"`
	DailyRewardsLastDay              int32       `db:"daily_rewards_last_day" json:"daily_rewards_last_day"`
	DailyRewardsBoxCount             int32       `db:"daily_rewards_box_count" json:"daily_rewards_box_count"`
	DailyRewardsCardsCountPerWeek    int32       `db:"daily_rewards_cards_count_per_week" json:"daily_rewards_cards_count_per_week"`
	LuckySpinCooltime                int32       `db:"lucky_spin_cooltime" json:"lucky_spin_cooltime"`
	DailyRewardsCooltime             int32       `db:"daily_rewards_cooltime" json:"daily_rewards_cooltime"`
	DailyRewardsCardClaimGracePeriod int32       `db:"daily_rewards_card_claim_grace_period" json:"daily_rewards_card_claim_grace_period"`
}

type GameType struct {
	ID          int32  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	EntranceFee int32  `db:"entrance_fee" json:"entrance_fee"`
}

type Item struct {
	ID        int32        `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	ItemType  GameItemType `db:"item_type" json:"item_type"`
	PriceType PriceType    `db:"price_type" json:"price_type"`
	Price     int32        `db:"price" json:"price"`
}

type LsReward struct {
	ID               int32      `db:"id" json:"id"`
	Type             RewardType `db:"type" json:"type"`
	Quantity         int32      `db:"quantity" json:"quantity"`
	SpawnProbability int32      `db:"spawn_probability" json:"spawn_probability"`
}

type Question struct {
	ID          int32              `db:"id" json:"id"`
	GameTypeID  int32              `db:"game_type_id" json:"game_type_id"`
	CategoryID  pgtype.Int4        `db:"category_id" json:"category_id"`
	Text        string             `db:"text" json:"text"`
	Explanation pgtype.Text        `db:"explanation" json:"explanation"`
	Choices     []string           `db:"choices" json:"choices"`
	AnswerIndex int32              `db:"answer_index" json:"answer_index"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RankingDate struct {
	ID              int32              `db:"id" json:"id"`
	DailyStartedAt  pgtype.Timestamptz `db:"daily_started_at" json:"daily_started_at"`
	DailyEndedAt    pgtype.Timestamptz `db:"daily_ended_at" json:"daily_ended_at"`
	WeeklyStartedAt pgtype.Timestamptz `db:"weekly_started_at" json:"weekly_started_at"`
	WeeklyEndedAt   pgtype.Timestamptz `db:"weekly_ended_at" json:"weekly_ended_at"`
}

type Stage struct {
	ID            int32              `db:"id" json:"id"`
	UserID        int64              `db:"user_id" json:"user_id"`
	GameTypeID    int32              `db:"game_type_id" json:"game_type_id"`
	CategoryID    pgtype.Int4        `db:"category_id" json:"category_id"`
	StageProgress int32              `db:"stage_progress" json:"stage_progress"`
	CoinRewards   int32              `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards  int32              `db:"crown_rewards" json:"crown_rewards"`
	IsClaimed     bool               `db:"is_claimed" json:"is_claimed"`
	IsQuit        bool               `db:"is_quit" json:"is_quit"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	QuitedAt      pgtype.Timestamptz `db:"quited_at" json:"quited_at"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	OauthID      pgtype.UUID        `db:"oauth_id" json:"oauth_id"`
	PublicID     pgtype.UUID        `db:"public_id" json:"public_id"`
	Nickname     string             `db:"nickname" json:"nickname"`
	ProfileIndex int32              `db:"profile_index" json:"profile_index"`
	CrownAmount  int32              `db:"crown_amount" json:"crown_amount"`
	GemBalance   int32              `db:"gem_balance" json:"gem_balance"`
	CoinBalance  int32              `db:"coin_balance" json:"coin_balance"`
	HintQuantity int32              `db:"hint_quantity" json:"hint_quantity"`
	SkipQuantity int32              `db:"skip_quantity" json:"skip_quantity"`
	CountryCode  string             `db:"country_code" json:"country_code"`
	IsDeleted    bool               `db:"is_deleted" json:"is_deleted"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type UserDrBoxClaim struct {
	ID        int64              `db:"id" json:"id"`
	UserID    int64              `db:"user_id" json:"user_id"`
	BoxID     int32              `db:"box_id" json:"box_id"`
	ClaimedAt pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
}

type UserDrCardClaim struct {
	ID        int64              `db:"id" json:"id"`
	UserID    int64              `db:"user_id" json:"user_id"`
	CardID    int32              `db:"card_id" json:"card_id"`
	ClaimedAt pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
}

type UserLsClaim struct {
	ID              int64              `db:"id" json:"id"`
	UserID          int64              `db:"user_id" json:"user_id"`
	RewardID        int32              `db:"reward_id" json:"reward_id"`
	QuantityAtClaim int32              `db:"quantity_at_claim" json:"quantity_at_claim"`
	TypeAtClaim     RewardType         `db:"type_at_claim" json:"type_at_claim"`
	ClaimedAt       pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
}

type UserLsSpin struct {
	ID        int64              `db:"id" json:"id"`
	UserID    int64              `db:"user_id" json:"user_id"`
	RewardID  int32              `db:"reward_id" json:"reward_id"`
	WasAds    bool               `db:"was_ads" json:"was_ads"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

type UserProgress struct {
	UserID     int64              `db:"user_id" json:"user_id"`
	QuestionID int32              `db:"question_id" json:"question_id"`
	Status     QuestionStatus     `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserQuestionStat struct {
	ID                    int64              `db:"id" json:"id"`
	UserID                int64              `db:"user_id" json:"user_id"`
	CategoryName          string             `db:"category_name" json:"category_name"`
	AnsweredQuestionCount int32              `db:"answered_question_count" json:"answered_question_count"`
	TotalQuestionCount    int32              `db:"total_question_count" json:"total_question_count"`
	CorrectQuestionCount  int32              `db:"correct_question_count" json:"correct_question_count"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
