// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Items available in the system (inventory, products, etc.)
type Item struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	Price       pgtype.Numeric     `db:"price" json:"price"`
	Quantity    int32              `db:"quantity" json:"quantity"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Transaction history for items and users
type Transaction struct {
	ID              int64              `db:"id" json:"id"`
	UserID          int64              `db:"user_id" json:"user_id"`
	ItemID          int64              `db:"item_id" json:"item_id"`
	TransactionType string             `db:"transaction_type" json:"transaction_type"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	Amount          pgtype.Numeric     `db:"amount" json:"amount"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Application users with soft delete support
type User struct {
	ID int64 `db:"id" json:"id"`
	// Public-facing UUID for external APIs
	PublicID    pgtype.UUID        `db:"public_id" json:"public_id"`
	Email       string             `db:"email" json:"email"`
	Username    string             `db:"username" json:"username"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Soft delete timestamp - NULL means active user
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
