// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: questions.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateQuestionsParams struct {
	GameTypeID  int32       `db:"game_type_id" json:"game_type_id"`
	CategoryID  pgtype.Int4 `db:"category_id" json:"category_id"`
	Text        string      `db:"text" json:"text"`
	Choices     []string    `db:"choices" json:"choices"`
	Explanation pgtype.Text `db:"explanation" json:"explanation"`
	AnswerIndex int32       `db:"answer_index" json:"answer_index"`
}

const getAllQuestions = `-- name: GetAllQuestions :many
SELECT id, game_type_id, category_id, text, explanation, choices, answer_index, created_at
FROM questions
`

// GetAllQuestions
//
//	SELECT id, game_type_id, category_id, text, explanation, choices, answer_index, created_at
//	FROM questions
func (q *Queries) GetAllQuestions(ctx context.Context) ([]Question, error) {
	rows, err := q.db.Query(ctx, getAllQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.GameTypeID,
			&i.CategoryID,
			&i.Text,
			&i.Explanation,
			&i.Choices,
			&i.AnswerIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionById = `-- name: GetQuestionById :one
SELECT id, game_type_id, category_id, text, explanation, choices, answer_index, created_at
FROM questions
WHERE id = $1
`

// GetQuestionById
//
//	SELECT id, game_type_id, category_id, text, explanation, choices, answer_index, created_at
//	FROM questions
//	WHERE id = $1
func (q *Queries) GetQuestionById(ctx context.Context, id int32) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionById, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.GameTypeID,
		&i.CategoryID,
		&i.Text,
		&i.Explanation,
		&i.Choices,
		&i.AnswerIndex,
		&i.CreatedAt,
	)
	return i, err
}

const isQuestionAnswerCorrect = `-- name: IsQuestionAnswerCorrect :one
SELECT COUNT(*) > 0
FROM questions
WHERE id = $1
  AND answer_index = $2
  AND game_type_id = $3
`

type IsQuestionAnswerCorrectParams struct {
	ID          int32 `db:"id" json:"id"`
	AnswerIndex int32 `db:"answer_index" json:"answer_index"`
	GameTypeID  int32 `db:"game_type_id" json:"game_type_id"`
}

// IsQuestionAnswerCorrect
//
//	SELECT COUNT(*) > 0
//	FROM questions
//	WHERE id = $1
//	  AND answer_index = $2
//	  AND game_type_id = $3
func (q *Queries) IsQuestionAnswerCorrect(ctx context.Context, arg IsQuestionAnswerCorrectParams) (bool, error) {
	row := q.db.QueryRow(ctx, isQuestionAnswerCorrect, arg.ID, arg.AnswerIndex, arg.GameTypeID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
