// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ranking_date.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyDate = `-- name: GetDailyDate :one
SELECT daily_started_at,
    daily_ended_at
FROM ranking_dates
`

type GetDailyDateRow struct {
	DailyStartedAt pgtype.Timestamptz `db:"daily_started_at" json:"daily_started_at"`
	DailyEndedAt   pgtype.Timestamptz `db:"daily_ended_at" json:"daily_ended_at"`
}

// GetDailyDate
//
//	SELECT daily_started_at,
//	    daily_ended_at
//	FROM ranking_dates
func (q *Queries) GetDailyDate(ctx context.Context) (GetDailyDateRow, error) {
	row := q.db.QueryRow(ctx, getDailyDate)
	var i GetDailyDateRow
	err := row.Scan(&i.DailyStartedAt, &i.DailyEndedAt)
	return i, err
}

const getWeeklyDate = `-- name: GetWeeklyDate :one
SELECT weekly_started_at,
    weekly_ended_at
FROM ranking_dates
`

type GetWeeklyDateRow struct {
	WeeklyStartedAt pgtype.Timestamptz `db:"weekly_started_at" json:"weekly_started_at"`
	WeeklyEndedAt   pgtype.Timestamptz `db:"weekly_ended_at" json:"weekly_ended_at"`
}

// GetWeeklyDate
//
//	SELECT weekly_started_at,
//	    weekly_ended_at
//	FROM ranking_dates
func (q *Queries) GetWeeklyDate(ctx context.Context) (GetWeeklyDateRow, error) {
	row := q.db.QueryRow(ctx, getWeeklyDate)
	var i GetWeeklyDateRow
	err := row.Scan(&i.WeeklyStartedAt, &i.WeeklyEndedAt)
	return i, err
}

const insertDailyDate = `-- name: InsertDailyDate :one
INSERT INTO ranking_dates (
        daily_started_at,
        daily_ended_at,
        weekly_started_at,
        weekly_ended_at
    )
VALUES ($1, $2, $3, $4)
RETURNING id, daily_started_at, daily_ended_at, weekly_started_at, weekly_ended_at
`

type InsertDailyDateParams struct {
	DailyStartedAt  pgtype.Timestamptz `db:"daily_started_at" json:"daily_started_at"`
	DailyEndedAt    pgtype.Timestamptz `db:"daily_ended_at" json:"daily_ended_at"`
	WeeklyStartedAt pgtype.Timestamptz `db:"weekly_started_at" json:"weekly_started_at"`
	WeeklyEndedAt   pgtype.Timestamptz `db:"weekly_ended_at" json:"weekly_ended_at"`
}

// InsertDailyDate
//
//	INSERT INTO ranking_dates (
//	        daily_started_at,
//	        daily_ended_at,
//	        weekly_started_at,
//	        weekly_ended_at
//	    )
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, daily_started_at, daily_ended_at, weekly_started_at, weekly_ended_at
func (q *Queries) InsertDailyDate(ctx context.Context, arg InsertDailyDateParams) (RankingDate, error) {
	row := q.db.QueryRow(ctx, insertDailyDate,
		arg.DailyStartedAt,
		arg.DailyEndedAt,
		arg.WeeklyStartedAt,
		arg.WeeklyEndedAt,
	)
	var i RankingDate
	err := row.Scan(
		&i.ID,
		&i.DailyStartedAt,
		&i.DailyEndedAt,
		&i.WeeklyStartedAt,
		&i.WeeklyEndedAt,
	)
	return i, err
}

const insertWeeklyDate = `-- name: InsertWeeklyDate :one
INSERT INTO ranking_dates (
        daily_started_at,
        daily_ended_at,
        weekly_started_at,
        weekly_ended_at
    )
VALUES ($1, $2, $3, $4)
RETURNING id, daily_started_at, daily_ended_at, weekly_started_at, weekly_ended_at
`

type InsertWeeklyDateParams struct {
	DailyStartedAt  pgtype.Timestamptz `db:"daily_started_at" json:"daily_started_at"`
	DailyEndedAt    pgtype.Timestamptz `db:"daily_ended_at" json:"daily_ended_at"`
	WeeklyStartedAt pgtype.Timestamptz `db:"weekly_started_at" json:"weekly_started_at"`
	WeeklyEndedAt   pgtype.Timestamptz `db:"weekly_ended_at" json:"weekly_ended_at"`
}

// InsertWeeklyDate
//
//	INSERT INTO ranking_dates (
//	        daily_started_at,
//	        daily_ended_at,
//	        weekly_started_at,
//	        weekly_ended_at
//	    )
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, daily_started_at, daily_ended_at, weekly_started_at, weekly_ended_at
func (q *Queries) InsertWeeklyDate(ctx context.Context, arg InsertWeeklyDateParams) (RankingDate, error) {
	row := q.db.QueryRow(ctx, insertWeeklyDate,
		arg.DailyStartedAt,
		arg.DailyEndedAt,
		arg.WeeklyStartedAt,
		arg.WeeklyEndedAt,
	)
	var i RankingDate
	err := row.Scan(
		&i.ID,
		&i.DailyStartedAt,
		&i.DailyEndedAt,
		&i.WeeklyStartedAt,
		&i.WeeklyEndedAt,
	)
	return i, err
}

const updateDailyDate = `-- name: UpdateDailyDate :exec
UPDATE ranking_dates
SET daily_started_at = $1,
    daily_ended_at = $2
`

type UpdateDailyDateParams struct {
	DailyStartedAt pgtype.Timestamptz `db:"daily_started_at" json:"daily_started_at"`
	DailyEndedAt   pgtype.Timestamptz `db:"daily_ended_at" json:"daily_ended_at"`
}

// UpdateDailyDate
//
//	UPDATE ranking_dates
//	SET daily_started_at = $1,
//	    daily_ended_at = $2
func (q *Queries) UpdateDailyDate(ctx context.Context, arg UpdateDailyDateParams) error {
	_, err := q.db.Exec(ctx, updateDailyDate, arg.DailyStartedAt, arg.DailyEndedAt)
	return err
}

const updateWeeklyDate = `-- name: UpdateWeeklyDate :exec
UPDATE ranking_dates
SET weekly_started_at = $1,
    weekly_ended_at = $2
`

type UpdateWeeklyDateParams struct {
	WeeklyStartedAt pgtype.Timestamptz `db:"weekly_started_at" json:"weekly_started_at"`
	WeeklyEndedAt   pgtype.Timestamptz `db:"weekly_ended_at" json:"weekly_ended_at"`
}

// UpdateWeeklyDate
//
//	UPDATE ranking_dates
//	SET weekly_started_at = $1,
//	    weekly_ended_at = $2
func (q *Queries) UpdateWeeklyDate(ctx context.Context, arg UpdateWeeklyDateParams) error {
	_, err := q.db.Exec(ctx, updateWeeklyDate, arg.WeeklyStartedAt, arg.WeeklyEndedAt)
	return err
}
