// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stages.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimClassicStageRewards = `-- name: ClaimClassicStageRewards :exec
UPDATE stages
SET coin_rewards  = 0,
    crown_rewards = 0,
    is_claimed= TRUE
WHERE user_id = $1
  AND game_type_id = 0
  AND category_id = $2
`

type ClaimClassicStageRewardsParams struct {
	UserID     int64       `db:"user_id" json:"user_id"`
	CategoryID pgtype.Int4 `db:"category_id" json:"category_id"`
}

// ClaimClassicStageRewards
//
//	UPDATE stages
//	SET coin_rewards  = 0,
//	    crown_rewards = 0,
//	    is_claimed= TRUE
//	WHERE user_id = $1
//	  AND game_type_id = 0
//	  AND category_id = $2
func (q *Queries) ClaimClassicStageRewards(ctx context.Context, arg ClaimClassicStageRewardsParams) error {
	_, err := q.db.Exec(ctx, claimClassicStageRewards, arg.UserID, arg.CategoryID)
	return err
}

const claimStageRewards = `-- name: ClaimStageRewards :exec
UPDATE stages
SET coin_rewards  = 0,
    crown_rewards = 0,
    is_claimed= TRUE
WHERE user_id = $1
  AND game_type_id = $2
`

type ClaimStageRewardsParams struct {
	UserID     int64 `db:"user_id" json:"user_id"`
	GameTypeID int32 `db:"game_type_id" json:"game_type_id"`
}

// ClaimStageRewards
//
//	UPDATE stages
//	SET coin_rewards  = 0,
//	    crown_rewards = 0,
//	    is_claimed= TRUE
//	WHERE user_id = $1
//	  AND game_type_id = $2
func (q *Queries) ClaimStageRewards(ctx context.Context, arg ClaimStageRewardsParams) error {
	_, err := q.db.Exec(ctx, claimStageRewards, arg.UserID, arg.GameTypeID)
	return err
}

const createStage = `-- name: CreateStage :one
INSERT INTO stages
(user_id, game_type_id, stage_progress, coin_rewards, crown_rewards, category_id, updated_at, is_claimed)
VALUES ($1, $2, $3, $4, $5, $6, $7, FALSE)
RETURNING id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
`

type CreateStageParams struct {
	UserID        int64              `db:"user_id" json:"user_id"`
	GameTypeID    int32              `db:"game_type_id" json:"game_type_id"`
	StageProgress int32              `db:"stage_progress" json:"stage_progress"`
	CoinRewards   int32              `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards  int32              `db:"crown_rewards" json:"crown_rewards"`
	CategoryID    pgtype.Int4        `db:"category_id" json:"category_id"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// CreateStage
//
//	INSERT INTO stages
//	(user_id, game_type_id, stage_progress, coin_rewards, crown_rewards, category_id, updated_at, is_claimed)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, FALSE)
//	RETURNING id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStage,
		arg.UserID,
		arg.GameTypeID,
		arg.StageProgress,
		arg.CoinRewards,
		arg.CrownRewards,
		arg.CategoryID,
		arg.UpdatedAt,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameTypeID,
		&i.CategoryID,
		&i.StageProgress,
		&i.CoinRewards,
		&i.CrownRewards,
		&i.IsClaimed,
		&i.IsQuit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuitedAt,
	)
	return i, err
}

const createStagesWithoutCategory = `-- name: CreateStagesWithoutCategory :one
INSERT INTO stages
(user_id, game_type_id, stage_progress, coin_rewards, crown_rewards, updated_at, is_claimed)
VALUES ($1, $2, $3, $4, $5, $6, FALSE)
RETURNING id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
`

type CreateStagesWithoutCategoryParams struct {
	UserID        int64              `db:"user_id" json:"user_id"`
	GameTypeID    int32              `db:"game_type_id" json:"game_type_id"`
	StageProgress int32              `db:"stage_progress" json:"stage_progress"`
	CoinRewards   int32              `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards  int32              `db:"crown_rewards" json:"crown_rewards"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// CreateStagesWithoutCategory
//
//	INSERT INTO stages
//	(user_id, game_type_id, stage_progress, coin_rewards, crown_rewards, updated_at, is_claimed)
//	VALUES ($1, $2, $3, $4, $5, $6, FALSE)
//	RETURNING id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
func (q *Queries) CreateStagesWithoutCategory(ctx context.Context, arg CreateStagesWithoutCategoryParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStagesWithoutCategory,
		arg.UserID,
		arg.GameTypeID,
		arg.StageProgress,
		arg.CoinRewards,
		arg.CrownRewards,
		arg.UpdatedAt,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameTypeID,
		&i.CategoryID,
		&i.StageProgress,
		&i.CoinRewards,
		&i.CrownRewards,
		&i.IsClaimed,
		&i.IsQuit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuitedAt,
	)
	return i, err
}

const deleteStage = `-- name: DeleteStage :exec
DELETE
FROM stages
WHERE user_id = $1
`

// DeleteStage
//
//	DELETE
//	FROM stages
//	WHERE user_id = $1
func (q *Queries) DeleteStage(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteStage, userID)
	return err
}

const getStageByUserId = `-- name: GetStageByUserId :one
SELECT id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
FROM stages
WHERE user_id = $1
`

// GetStageByUserId
//
//	SELECT id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
//	FROM stages
//	WHERE user_id = $1
func (q *Queries) GetStageByUserId(ctx context.Context, userID int64) (Stage, error) {
	row := q.db.QueryRow(ctx, getStageByUserId, userID)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameTypeID,
		&i.CategoryID,
		&i.StageProgress,
		&i.CoinRewards,
		&i.CrownRewards,
		&i.IsClaimed,
		&i.IsQuit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuitedAt,
	)
	return i, err
}

const getStageByUserIdAndGameTypeId = `-- name: GetStageByUserIdAndGameTypeId :one
SELECT id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
FROM stages
WHERE user_id = $1
  AND game_type_id = $2
LIMIT 1
`

type GetStageByUserIdAndGameTypeIdParams struct {
	UserID     int64 `db:"user_id" json:"user_id"`
	GameTypeID int32 `db:"game_type_id" json:"game_type_id"`
}

// GetStageByUserIdAndGameTypeId
//
//	SELECT id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
//	FROM stages
//	WHERE user_id = $1
//	  AND game_type_id = $2
//	LIMIT 1
func (q *Queries) GetStageByUserIdAndGameTypeId(ctx context.Context, arg GetStageByUserIdAndGameTypeIdParams) (Stage, error) {
	row := q.db.QueryRow(ctx, getStageByUserIdAndGameTypeId, arg.UserID, arg.GameTypeID)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameTypeID,
		&i.CategoryID,
		&i.StageProgress,
		&i.CoinRewards,
		&i.CrownRewards,
		&i.IsClaimed,
		&i.IsQuit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuitedAt,
	)
	return i, err
}

const getStageClassicMode = `-- name: GetStageClassicMode :one
SELECT id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
FROM stages
WHERE user_id = $1
  AND game_type_id = $2
  AND category_id = $3
LIMIT 1
`

type GetStageClassicModeParams struct {
	UserID     int64       `db:"user_id" json:"user_id"`
	GameTypeID int32       `db:"game_type_id" json:"game_type_id"`
	CategoryID pgtype.Int4 `db:"category_id" json:"category_id"`
}

// GetStageClassicMode
//
//	SELECT id, user_id, game_type_id, category_id, stage_progress, coin_rewards, crown_rewards, is_claimed, is_quit, created_at, updated_at, quited_at
//	FROM stages
//	WHERE user_id = $1
//	  AND game_type_id = $2
//	  AND category_id = $3
//	LIMIT 1
func (q *Queries) GetStageClassicMode(ctx context.Context, arg GetStageClassicModeParams) (Stage, error) {
	row := q.db.QueryRow(ctx, getStageClassicMode, arg.UserID, arg.GameTypeID, arg.CategoryID)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameTypeID,
		&i.CategoryID,
		&i.StageProgress,
		&i.CoinRewards,
		&i.CrownRewards,
		&i.IsClaimed,
		&i.IsQuit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuitedAt,
	)
	return i, err
}

const getStageRewards = `-- name: GetStageRewards :one
SELECT coin_rewards,
       crown_rewards
FROM stages
WHERE user_id = $1
  AND game_type_id = $2
`

type GetStageRewardsParams struct {
	UserID     int64 `db:"user_id" json:"user_id"`
	GameTypeID int32 `db:"game_type_id" json:"game_type_id"`
}

type GetStageRewardsRow struct {
	CoinRewards  int32 `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards int32 `db:"crown_rewards" json:"crown_rewards"`
}

// GetStageRewards
//
//	SELECT coin_rewards,
//	       crown_rewards
//	FROM stages
//	WHERE user_id = $1
//	  AND game_type_id = $2
func (q *Queries) GetStageRewards(ctx context.Context, arg GetStageRewardsParams) (GetStageRewardsRow, error) {
	row := q.db.QueryRow(ctx, getStageRewards, arg.UserID, arg.GameTypeID)
	var i GetStageRewardsRow
	err := row.Scan(&i.CoinRewards, &i.CrownRewards)
	return i, err
}

const getStageRewardsWithCategoryId = `-- name: GetStageRewardsWithCategoryId :one
SELECT coin_rewards,
       crown_rewards
FROM stages
WHERE user_id = $1
  AND game_type_id = 0
  AND category_id = $2
`

type GetStageRewardsWithCategoryIdParams struct {
	UserID     int64       `db:"user_id" json:"user_id"`
	CategoryID pgtype.Int4 `db:"category_id" json:"category_id"`
}

type GetStageRewardsWithCategoryIdRow struct {
	CoinRewards  int32 `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards int32 `db:"crown_rewards" json:"crown_rewards"`
}

// GetStageRewardsWithCategoryId
//
//	SELECT coin_rewards,
//	       crown_rewards
//	FROM stages
//	WHERE user_id = $1
//	  AND game_type_id = 0
//	  AND category_id = $2
func (q *Queries) GetStageRewardsWithCategoryId(ctx context.Context, arg GetStageRewardsWithCategoryIdParams) (GetStageRewardsWithCategoryIdRow, error) {
	row := q.db.QueryRow(ctx, getStageRewardsWithCategoryId, arg.UserID, arg.CategoryID)
	var i GetStageRewardsWithCategoryIdRow
	err := row.Scan(&i.CoinRewards, &i.CrownRewards)
	return i, err
}

const resetClassicModeStage = `-- name: ResetClassicModeStage :exec
UPDATE stages
SET stage_progress = 0,
    coin_rewards   = $2,
    crown_rewards  = $3,
    is_claimed= FALSE
WHERE user_id = $1
  AND game_type_id = 0
`

type ResetClassicModeStageParams struct {
	UserID       int64 `db:"user_id" json:"user_id"`
	CoinRewards  int32 `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards int32 `db:"crown_rewards" json:"crown_rewards"`
}

// ResetClassicModeStage
//
//	UPDATE stages
//	SET stage_progress = 0,
//	    coin_rewards   = $2,
//	    crown_rewards  = $3,
//	    is_claimed= FALSE
//	WHERE user_id = $1
//	  AND game_type_id = 0
func (q *Queries) ResetClassicModeStage(ctx context.Context, arg ResetClassicModeStageParams) error {
	_, err := q.db.Exec(ctx, resetClassicModeStage, arg.UserID, arg.CoinRewards, arg.CrownRewards)
	return err
}

const resetStage = `-- name: ResetStage :exec
UPDATE stages
SET stage_progress=0,
    coin_rewards=$3,
    crown_rewards=$4,
    is_claimed= FALSE
WHERE user_id = $1
  AND game_type_id = $2
`

type ResetStageParams struct {
	UserID       int64 `db:"user_id" json:"user_id"`
	GameTypeID   int32 `db:"game_type_id" json:"game_type_id"`
	CoinRewards  int32 `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards int32 `db:"crown_rewards" json:"crown_rewards"`
}

// ResetStage
//
//	UPDATE stages
//	SET stage_progress=0,
//	    coin_rewards=$3,
//	    crown_rewards=$4,
//	    is_claimed= FALSE
//	WHERE user_id = $1
//	  AND game_type_id = $2
func (q *Queries) ResetStage(ctx context.Context, arg ResetStageParams) error {
	_, err := q.db.Exec(ctx, resetStage,
		arg.UserID,
		arg.GameTypeID,
		arg.CoinRewards,
		arg.CrownRewards,
	)
	return err
}

const updateStageProgress = `-- name: UpdateStageProgress :exec
UPDATE stages
SET stage_progress = $3
WHERE user_id = $1
  AND game_type_id = $2
`

type UpdateStageProgressParams struct {
	UserID        int64 `db:"user_id" json:"user_id"`
	GameTypeID    int32 `db:"game_type_id" json:"game_type_id"`
	StageProgress int32 `db:"stage_progress" json:"stage_progress"`
}

// UpdateStageProgress
//
//	UPDATE stages
//	SET stage_progress = $3
//	WHERE user_id = $1
//	  AND game_type_id = $2
func (q *Queries) UpdateStageProgress(ctx context.Context, arg UpdateStageProgressParams) error {
	_, err := q.db.Exec(ctx, updateStageProgress, arg.UserID, arg.GameTypeID, arg.StageProgress)
	return err
}

const updateStageProgressAndRewards = `-- name: UpdateStageProgressAndRewards :exec
UPDATE stages
SET stage_progress = $4,
    coin_rewards   = $5,
    crown_rewards  = $6
WHERE user_id = $1
  AND game_type_id = $2
  AND category_id = $3
`

type UpdateStageProgressAndRewardsParams struct {
	UserID        int64       `db:"user_id" json:"user_id"`
	GameTypeID    int32       `db:"game_type_id" json:"game_type_id"`
	CategoryID    pgtype.Int4 `db:"category_id" json:"category_id"`
	StageProgress int32       `db:"stage_progress" json:"stage_progress"`
	CoinRewards   int32       `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards  int32       `db:"crown_rewards" json:"crown_rewards"`
}

// UpdateStageProgressAndRewards
//
//	UPDATE stages
//	SET stage_progress = $4,
//	    coin_rewards   = $5,
//	    crown_rewards  = $6
//	WHERE user_id = $1
//	  AND game_type_id = $2
//	  AND category_id = $3
func (q *Queries) UpdateStageProgressAndRewards(ctx context.Context, arg UpdateStageProgressAndRewardsParams) error {
	_, err := q.db.Exec(ctx, updateStageProgressAndRewards,
		arg.UserID,
		arg.GameTypeID,
		arg.CategoryID,
		arg.StageProgress,
		arg.CoinRewards,
		arg.CrownRewards,
	)
	return err
}

const updateStageProgressAndRewardsWithoutCategory = `-- name: UpdateStageProgressAndRewardsWithoutCategory :exec
UPDATE stages
SET stage_progress = $3,
    coin_rewards   = $4,
    crown_rewards  = $5
WHERE user_id = $1
  AND game_type_id = $2
`

type UpdateStageProgressAndRewardsWithoutCategoryParams struct {
	UserID        int64 `db:"user_id" json:"user_id"`
	GameTypeID    int32 `db:"game_type_id" json:"game_type_id"`
	StageProgress int32 `db:"stage_progress" json:"stage_progress"`
	CoinRewards   int32 `db:"coin_rewards" json:"coin_rewards"`
	CrownRewards  int32 `db:"crown_rewards" json:"crown_rewards"`
}

// UpdateStageProgressAndRewardsWithoutCategory
//
//	UPDATE stages
//	SET stage_progress = $3,
//	    coin_rewards   = $4,
//	    crown_rewards  = $5
//	WHERE user_id = $1
//	  AND game_type_id = $2
func (q *Queries) UpdateStageProgressAndRewardsWithoutCategory(ctx context.Context, arg UpdateStageProgressAndRewardsWithoutCategoryParams) error {
	_, err := q.db.Exec(ctx, updateStageProgressAndRewardsWithoutCategory,
		arg.UserID,
		arg.GameTypeID,
		arg.StageProgress,
		arg.CoinRewards,
		arg.CrownRewards,
	)
	return err
}
