// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

// CountUsers
//
//	SELECT COUNT(*) FROM users
//	WHERE deleted_at IS NULL
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    username,
    display_name
) VALUES (
    $1, $2, $3
) RETURNING id, public_id, email, username, display_name, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email       string      `db:"email" json:"email"`
	Username    string      `db:"username" json:"username"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
}

// CreateUser
//
//	INSERT INTO users (
//	    email,
//	    username,
//	    display_name
//	) VALUES (
//	    $1, $2, $3
//	) RETURNING id, public_id, email, username, display_name, created_at, updated_at, deleted_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

// GetUserByEmail
//
//	SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
//	WHERE email = $1 AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

// GetUserByID
//
//	SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
//	WHERE id = $1 AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
WHERE public_id = $1 AND deleted_at IS NULL
LIMIT 1
`

// GetUserByPublicID
//
//	SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
//	WHERE public_id = $1 AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetUserByPublicID(ctx context.Context, publicID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
WHERE username = $1 AND deleted_at IS NULL
LIMIT 1
`

// GetUserByUsername
//
//	SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
//	WHERE username = $1 AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users
WHERE id = $1
`

// HardDeleteUser
//
//	DELETE FROM users
//	WHERE id = $1
func (q *Queries) HardDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// ListUsers
//
//	SELECT id, public_id, email, username, display_name, created_at, updated_at, deleted_at FROM users
//	WHERE deleted_at IS NULL
//	ORDER BY created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// SoftDeleteUser
//
//	UPDATE users
//	SET deleted_at = NOW()
//	WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = COALESCE($2, email),
    username = COALESCE($3, username),
    display_name = COALESCE($4, display_name)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, public_id, email, username, display_name, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID          int64       `db:"id" json:"id"`
	Email       string      `db:"email" json:"email"`
	Username    string      `db:"username" json:"username"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
}

// UpdateUser
//
//	UPDATE users
//	SET
//	    email = COALESCE($2, email),
//	    username = COALESCE($3, username),
//	    display_name = COALESCE($4, display_name)
//	WHERE id = $1 AND deleted_at IS NULL
//	RETURNING id, public_id, email, username, display_name, created_at, updated_at, deleted_at
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
